### ISSUE TITLE
Raster pipe friendliness 

### ISSUE THREAD

**Issue by loicdtx** [edzer/UseR2017#1]
You mention at the end of your tutorial that `raster` does not integrate too well with pipe-based workflows. I don't know where that idea came from (I've seen it [here](https://github.com/ropensci/unconf17/issues/54) as well), but I actually find that `raster`'s consistency makes it quite pipable. Try for instance:

```r
library(raster)

r <- system.file("external/rlogo.grd", package="raster") %>%
    raster() %>%
    crop(extent(1, 100, 1, 76 )) %>%
    projectRaster(crs='+proj=longlat') %>%
    aggregate(2) %>%
    calc(fun = function(x){x * 2}) %>%
    writeRaster(filename = '~/sandbox/rlogo_piped_processed.grd')
```
It doesn't do anything interesting :) but it works!! Also you can comment any of the intermediary lines and the chain would still work.

**Comment by edzer** [comment]
Fair point, Loic -- thanks!
